// Settings:
:stylesheet: site.css
:sectnums:
:experimental:
ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
endif::[]
ifdef::env-github[]
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

= Getting started

== Creating a backend project

Since the frontend depends on the backend to get data, we will get started with the latter, use Cargo to create a new Rust project.

[source,console]
----
$ cargo new backend --vcs none
----

NOTE: We use the `--vcs none` flag because we are planning on having both the backend and the frontend under a parent Git directory.

Then we can check that everything works running:

[source,console]
----
$ cargo run
» Hello World!
----

Cargo set the project for us and it already compiles and runs.

== A _"Hello World!"_ Server

Actix makes it really easy for us to get a web server up and running in no time. Install it as a dependency.

[source,console]
----
$ cargo add actix-web
----

And we can construct a _"Hello World"_ server using the following code in main.

[source,rs]
----
use actix_web::{get, App, HttpResponse, HttpServer, Responder};

#[get("/")]
async fn hello() -> impl Responder {
    HttpResponse::Ok().body("Hello world!")
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| App::new().service(hello))
        .bind(("127.0.0.1", 8080))?
        .run()
        .await
}
----

Then we run the code using `cargo run` and we can see the response when we request that route.

[source,console]
----
$ curl "http://localhost:8080"
» Hello World!
----
